events {}

http {

    upstream backend_rr {

        server app1:5000;
        server app2:5000;
        server app3:5000;
    }

    upstream backend_lc {

        least_conn;

        server app1:5000;
        server app2:5000;
        server app3:5000;
    }

    upstream backend_weight {

        server app1:5000 weight=5;
        server app2:5000 weight=3;
        server app3:5000 weight=2;
    }

    upstream backend_iphash {

        ip_hash;

        server app1:5000;
        server app2:5000;
        server app3:5000;
    }

    server {

        listen 80;

        location /rr {
            proxy_pass http://backend_rr/;
        }

        location /lc {
            proxy_pass http://backend_lc/slow;
        }

        location /weight {
            proxy_pass http://backend_weight/;
        }

        location /sticky {
            proxy_pass http://backend_iphash/;
        }
    }
}